### ISSUE TITLE
Tag support?

### ISSUE THREAD

**Issue by Martin-Luckow** [ParamountVentures/AzureNotificationHubsDemo#1]
Hi Steven.

As far as I can see, the sample does not support tags.
Is there a version of the plugin which supports tags?

Best Regards

Martin

**Comment by stevenlivz** [comment]
Let me look into it Martin before I say where this is .... i've been on other things but from memory tag support wasn't far away (i think!). 

cheers,
steven

**Comment by stevenlivz** [comment]
Hi Martin - I have now added Tag support for Windows Devices in this demo - I will add the others at some point. I have also forked the original plugin to add tag support which you can find at:

https://github.com/ParamountVentures/cordova-plugin-azure-notificationhub

This fork is the plugin that is used in this sample.

Does that help?

**Comment by Martin-Luckow** [comment]
Hi Steven.

Thank you. 
Past days, I tried it by myself and learned a lot, I dont want to learn  - my version works for Universal only and I will takeover yours :)

In fact, this plugin ist the one, which is most close to what – I suppose –Azure-affine Cordovadians need: The old PushPlugin is deprecated, its successor has no binding to Azure, is poorly documented and and and.

Btw: I found, that a successful registration ends in a first call of the notification handler. I never had a success-break in the registration callback.  Same experience?

Best Regards from Munich

Martin

Von: Steven Livingstone-Perez [mailto:notifications@github.com] 
Gesendet: Mittwoch, 7. Oktober 2015 17:07
An: ParamountVentures/AzureNotificationHubsDemo AzureNotificationHubsDemo@noreply.github.com
Cc: Dr. Martin Luckow martin.luckow@gmail.com
Betreff: Re: [AzureNotificationHubsDemo] Tag support? (#1)

Hi Martin - I have now added Tag support for Windows Devices in this demo - I will add the others at some point. I have also forked the original plugin to add tag support which you can find at:

https://github.com/ParamountVentures/cordova-plugin-azure-notificationhub

This fork is the plugin that is used in this sample.

Does that help?

**Comment by stevenlivz** [comment]
Have you looked at my cross platform demo to which i added toasts (the plugin i use in this version doesn't do toasts on iOS/android as you may have noticed)? It doesn't yet support tags but it actually uses this sample plugin as the basis for the Windows Universal and uses the officially supported push plugin for the iOS/Android.:

https://github.com/ParamountVentures/ventures-paramount-phonegap-plugin-notificationhubs

A sample using it is at:

https://github.com/ParamountVentures/AzureNotificationHubsCrossPlatformDemo

I will be adding tag support to that as well so maybe you want to use that one. I'll probably add tags to that demo over this one mainly as it is a fuller solution for all platforms (just without tags ... yet!).

All the best !
/steven

**Comment by stevenlivz** [comment]
To close this, tag support demo now added for Windows, iOS and Android at

https://github.com/ParamountVentures/ventures-paramount-phonegap-plugin-notificationhubs

A sample using it is at:

https://github.com/ParamountVentures/AzureNotificationHubsCrossPlatformDemo
